export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const FAVORITE_BLOG = "FAVORITE_BLOG"
export const GET_FAVORITE_BLOGS = "GET_FAVORITE_BLOGS"
export const SHOW_FAVORITE_BLOGS = "SHOW_FAVORITE_BLOGS"

export const ADD_ERROR = "ADD_ERROR";
export const REMOVE_ERROR = "REMOVE_ERROR";

export const LOAD_BLOGS = "LOAD_BLOGS";
export const REMOVE_BLOG = "REMOVE_BLOG";
export const CREATE_BLOG = "CREATE_BLOG";
export const UPDATE_BLOG = "UPDATE_BLOG";

export const LOAD_POSTS = "LOAD_POSTS";
export const REMOVE_POST = "REMOVE_POST";
export const REMOVE_ALL_POSTS = "REMOVE_ALL_POSTS";
export const CREATE_POST = "CREATE_POST";
export const UPDATE_POST = "UPDATE_POST";